"""initial schema

Revision ID: 08fcb977d4e6
Revises:
Create Date: 2024-06-20 16:26:39.103445

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "08fcb977d4e6"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "casa_account",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("account_num", sa.String(length=32), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("balance", sa.DECIMAL(precision=14, scale=2), nullable=False),
        sa.Column("avail_balance", sa.DECIMAL(precision=14, scale=2), nullable=False),
        sa.Column("status", sa.Enum("ACTIVE", "SUSPENDED", "CLOSED", name="statusenum"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("account_currency_idx", "casa_account", ["account_num", "currency"], unique=True)
    op.create_table(
        "casa_transfer",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ref_id", sa.String(length=32), nullable=False),
        sa.Column("trx_date", sa.String(length=10), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("amount", sa.DECIMAL(precision=14, scale=2), nullable=False),
        sa.Column("memo", sa.String(length=100), nullable=False),
        sa.Column("debit_account_num", sa.String(length=32), nullable=False),
        sa.Column("credit_account_num", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ref_id"),
    )
    op.create_index(op.f("ix_casa_transfer_trx_date"), "casa_transfer", ["trx_date"], unique=False)
    op.create_table(
        "casa_transaction",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ref_id", sa.String(length=32), nullable=False),
        sa.Column("trx_date", sa.String(length=10), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("amount", sa.DECIMAL(precision=14, scale=2), nullable=False),
        sa.Column("memo", sa.String(length=100), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["casa_account.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("account_trx_date_idx", "casa_transaction", ["account_id", "trx_date"], unique=False)
    op.create_index(op.f("ix_casa_transaction_ref_id"), "casa_transaction", ["ref_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_casa_transaction_ref_id"), table_name="casa_transaction")
    op.drop_index("account_trx_date_idx", table_name="casa_transaction")
    op.drop_table("casa_transaction")
    op.drop_index(op.f("ix_casa_transfer_trx_date"), table_name="casa_transfer")
    op.drop_table("casa_transfer")
    op.drop_index("account_currency_idx", table_name="casa_account")
    op.drop_table("casa_account")
    # ### end Alembic commands ###
