"""add indexes

Revision ID: 603032d532f6
Revises: 3deea3897ca4
Create Date: 2024-06-25 19:52:12.478166

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "603032d532f6"
down_revision: Union[str, None] = "3deea3897ca4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("account_status_idx", "casa_account", ["account_num", "status"], unique=True)
    op.create_index("account_date_idx", "casa_transaction", ["account_id", "trx_date"], unique=False)
    op.create_index(op.f("ix_casa_transaction_trx_date"), "casa_transaction", ["trx_date"], unique=False)
    op.create_index(op.f("ix_casa_transfer_trx_date"), "casa_transfer", ["trx_date"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_casa_transfer_trx_date"), table_name="casa_transfer")
    op.drop_index(op.f("ix_casa_transaction_trx_date"), table_name="casa_transaction")
    op.drop_index("account_date_idx", table_name="casa_transaction")
    op.drop_index("account_status_idx", table_name="casa_account")
    # ### end Alembic commands ###
