"""auto update casa_account.updated_at

Revision ID: 76a6233e66f7
Revises: cf6d42a9a9a3
Create Date: 2024-06-25 14:42:50.431694

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "76a6233e66f7"
down_revision: Union[str, None] = "cf6d42a9a9a3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
